Fix Android cross-compilation error
39cb8b69882df46e6caa967873bebe13ada29f38 introduced a cross-compilation error
for Android where a build would fail with

[...]
pcl/common/include/pcl/pcl_macros.h:394:4: error: #error aligned_malloc not
supported on your platform
   #error aligned_malloc not supported on your platform
    ^
pcl/common/include/pcl/pcl_macros.h:410:4: error: #error aligned_free not
supported on your platform
   #error aligned_free not supported on your platform
    ^
[...]

This patch adds a new CPP branch for Android to pcl_macros.h. The calls to
memalign() and free() were checked against the malloc.h files from the
Android NDK r13b.