Fix compile error C2440 of pcl_visualization on MSVC
The pcl_visualization occur compile error C2440 on MSVC.
This error occurs because that can not directly cast to enum type from
double type in MSVC.
It must explicitly cast to int type from double type before cast to enum
type.