Fix 'undefined reference' linker errors
A simple program with the main function consisting only of one line:

pcl::octree::OctreePointCloudAdjacency<pcl::PointXYZRGBA> octree (0.5f);

will fail to be linked with a number of 'undefined reference' errors
like this:

    octree_pointcloud_adjacency.hpp:48: undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZRGBA, pcl::octree::OctreePointCloudAdjacencyContainer<pcl::PointXYZRGBA, pcl::PointXYZRGBA>, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreePointCloudAdjacencyContainer<pcl::PointXYZRGBA, pcl::PointXYZRGBA>, pcl::octree::OctreeContainerEmpty> >::OctreePointCloud(double)'

This commit adds an include that pulls in template definitions for the
Octree components, therefore allowing the compiler to instantiate
appropriate templates as needed.