fixing compile error (http://pastebin.com/ZD8NezKn)
pcl/common/include/pcl/point_traits.h(153) : error C2499: 'pcl::traits::fieldList<PointT>' : a class cannot be its own base class
This is the "first" error, but it can be traced to missing template types. Adding these types fixes
the compilation error. I've found the hint here: http://www.pcl-users.org/failed-to-build-kinfu-td4032311.html

Note: I was building on Win7-64bit with MSVC2010 (SP1) in Debug mode.
Note#2: I'm not sure about correspondence_estimation_normal_shooting, cause pt_src is actually PointSource, not PointTarget
        but the comment says otherwise, it compiles at least.